[package]
name = "otpencrypt"
version = "0.1.0"
edition = "2021"
description = "One-time pad encryption tool"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
